In [1]:
import pandas as pd

In [2]:
usd = pd.read_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\usd_inr.csv"
)

oil = pd.read_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\oil_data.csv"
)

dxy = pd.read_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\dxy_data.csv"
)

nifty = pd.read_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\nifty_data.csv"
)

forex = pd.read_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\forex_reserves.csv"
)

inflation = pd.read_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\inflation.csv"
)

fpi = pd.read_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\fpi_master.csv"
)

In [3]:
datasets = [
    usd,
    oil,
    dxy,
    nifty,
    forex,
    inflation,
    fpi
]

for df in datasets:

    df['Date'] = pd.to_datetime(
        df['Date']
    )

In [4]:
for df in datasets:
    
    df.sort_values(
        'Date',
        inplace=True
    )

In [5]:
print(usd.columns)
print(oil.columns)
print(dxy.columns)
print(nifty.columns)
print(forex.columns)
print(inflation.columns)
print(fpi.columns)

Index(['Date', 'Adj Close', 'USD_INR', 'High', 'Low', 'Open', 'Volume',
       'returns', 'volatility', 'ma_30'],
      dtype='str')
Index(['Date', 'Adj Close', 'Oil', 'High', 'Low', 'Open', 'Volume',
       'oil_ma_30', 'oil_spike'],
      dtype='str')
Index(['Date', 'Adj Close', 'DXY', 'High', 'Low', 'Open', 'Volume',
       'dxy_change'],
      dtype='str')
Index(['Date', 'Adj Close', 'NIFTY', 'High', 'Low', 'Open', 'Volume',
       'market_return'],
      dtype='str')
Index(['Year', 'Month', 'ForexReserves', 'GoldReserves', 'TotalReserves',
       'MonthNum', 'Date'],
      dtype='str')
Index(['Date', 'CPI_Index', 'Inflation'], dtype='str')
Index(['Date', 'EquityFlow', 'DebtFlow', 'NetFlow', 'FII_Outflow',
       'FlowChange', 'Flow_MA_3'],
      dtype='str')

In [6]:
usd.rename(
    columns={
        'Close':'USD_INR'
    },
    inplace=True
)

In [ ]:
oil.rename(
    columns={
        'Close':'OilPrice'
    },
    inplace=True
    
)

In [8]:
dxy.rename(
    columns={
        'Close':'DXY'
    },
    inplace=True
)

In [9]:
nifty.rename(
    columns={
        'Close':'Nifty'
    },
    inplace=True
)

In [12]:
oil.head()

,Date,Adj Close,Oil,High,Low,Open,Volume,oil_ma_30,oil_spike
0,2015-01-02,56.419998,56.419998,58.220001,55.520000,57.630001,16707,NaN,0
1,2015-01-05,53.110001,53.110001,56.290001,52.669998,56.290001,30065,NaN,0
2,2015-01-06,51.099998,51.099998,53.520000,50.529999,53.230000,35494,NaN,0
3,2015-01-07,51.150002,51.150002,51.840000,49.680000,51.060001,37082,NaN,0
4,2015-01-08,50.959999,50.959999,51.889999,49.820000,51.000000,29469,NaN,0

In [14]:
nifty

,Date,Adj Close,NIFTY,High,Low,Open,Volume,market_return
0,2015-01-02,8395.450195,8395.450195,8410.599609,8288.700195,8288.700195,101900,NaN
1,2015-01-05,8378.400391,8378.400391,8445.599609,8363.900391,8407.950195,118200,-0.002031
2,2015-01-06,8127.350098,8127.350098,8327.849609,8111.350098,8325.299805,172800,-0.029964
3,2015-01-07,8102.100098,8102.100098,8151.200195,8065.450195,8118.649902,164100,-0.003107
4,2015-01-08,8234.599609,8234.599609,8243.500000,8167.299805,8191.399902,143800,0.016354
...,...,...,...,...,...,...,...,...
2786,2026-04-30,23997.550781,23997.550781,24087.449219,23796.849609,23996.949219,505500,-0.007449
2787,2026-05-04,24119.300781,24119.300781,24290.199219,24004.750000,24063.550781,419100,0.005073
2788,2026-05-05,24032.800781,24032.800781,24081.699219,23882.050781,24052.599609,363300,-0.003586
2789,2026-05-06,24330.949219,24330.949219,24356.500000,23997.900391,24171.000000,429200,0.012406
2790,2026-05-07,24326.650391,24326.650391,24482.099609,24284.000000,24398.500000,0,-0.000177

In [15]:
usd = usd[['Date','USD_INR']]

oil = oil[['Date','Oil']]

dxy = dxy[['Date','DXY']]

nifty = nifty[['Date','NIFTY']]

forex = forex[[
    'Date',
    'ForexReserves',
    'GoldReserves',
    'TotalReserves'
]]

inflation = inflation[[
    'Date',
    'Inflation'
]]

fpi = fpi[[
    'Date',
    'NetFlow'
]]

In [16]:
master = usd.copy()

In [17]:
master = master.merge(
    oil,
    on='Date',
    how='left'
)

master = master.merge(
    dxy,
    on='Date',
    how='left'
)

master = master.merge(
    nifty,
    on='Date',
    how='left'
)

master = master.merge(
    forex,
    on='Date',
    how='left'
)

master = master.merge(
    inflation,
    on='Date',
    how='left'
)

master = master.merge(
    fpi,
    on='Date',
    how='left'
)

In [18]:
master.sort_values(
    'Date',
    inplace=True
)

In [20]:
master.ffill(
    inplace=True
)

,Date,USD_INR,Oil,DXY,NIFTY,ForexReserves,GoldReserves,TotalReserves,Inflation,NetFlow
0,2015-01-01,63.028000,NaN,NaN,NaN,303325.00,20183.20,328688.900,5.190000,33687.0
1,2015-01-02,63.028000,56.419998,91.080002,8395.450195,303325.00,20183.20,328688.900,5.190000,33687.0
2,2015-01-05,63.278000,53.110001,91.379997,8378.400391,303325.00,20183.20,328688.900,5.190000,33687.0
3,2015-01-06,63.338001,51.099998,91.500000,8127.350098,303325.00,20183.20,328688.900,5.190000,33687.0
4,2015-01-07,63.568001,51.150002,91.889999,8102.100098,303325.00,20183.20,328688.900,5.190000,33687.0
...,...,...,...,...,...,...,...,...,...,...
2948,2026-05-01,94.759102,108.169998,98.209999,23997.550781,552896.58,111262.36,687734.274,5.105778,-3008.0
2949,2026-05-04,94.903000,114.440002,98.470001,24119.300781,552896.58,111262.36,687734.274,5.105778,-3008.0
2950,2026-05-05,95.259399,109.870003,98.480003,24032.800781,552896.58,111262.36,687734.274,5.105778,-3008.0
2951,2026-05-06,95.182999,101.269997,98.019997,24330.949219,552896.58,111262.36,687734.274,5.105778,-3008.0
2952,2026-05-07,94.250000,100.860001,97.987000,24326.650391,552896.58,111262.36,687734.274,5.105778,-3008.0

In [21]:
master.dropna(
    inplace=True
)

In [22]:
master['INR_Return'] = (
    master['USD_INR']
    .pct_change()
)

In [24]:
master['Oil_Change'] = (
    master['Oil']
    .pct_change()
)

In [25]:
master['DXY_Change'] = (
    master['DXY']
    .pct_change()
)

In [26]:
master['INR_Volatility_7D'] = (
    master['USD_INR']
    .rolling(7)
    .std()
)

In [27]:
master['CrisisFlag'] = (
    (
        master['INR_Return'] > 0.01
    )
    &
    (
        master['Oil_Change'] > 0.03
    )
).astype(int)

In [28]:
master.dropna(
    inplace=True
)

master.reset_index(
    drop=True,
    inplace=True
)

In [29]:
print(master.head())

print(master.info())

print(master.isnull().sum())

        Date    USD_INR        Oil        DXY        NIFTY  ForexReserves  \
0 2015-01-12  62.348000  47.430000  91.980003  8323.000000       303325.0
1 2015-01-13  62.068001  46.590000  92.309998  8299.400391       303325.0
2 2015-01-14  61.973000  48.689999  92.160004  8277.549805       303325.0
3 2015-01-15  62.088001  47.669998  92.349998  8494.150391       303325.0
4 2015-01-16  62.057999  47.689999  92.519997  8513.799805       303325.0

   GoldReserves  TotalReserves  Inflation  NetFlow  INR_Return  Oil_Change  \
0       20183.2       328688.9       5.19  33687.0   -0.005106   -0.053482
1       20183.2       328688.9       5.19  33687.0   -0.004491   -0.017710
2       20183.2       328688.9       5.19  33687.0   -0.001531    0.045074
3       20183.2       328688.9       5.19  33687.0    0.001856   -0.020949
4       20183.2       328688.9       5.19  33687.0   -0.000483    0.000420

   DXY_Change  INR_Volatility_7D  CrisisFlag
0    0.000435           0.426016           0
1    0.003588           0.571917           0
2   -0.001625           0.648788           0
3    0.002062           0.631115           0
4    0.001841           0.470553           0
<class 'pandas.DataFrame'>
RangeIndex: 2946 entries, 0 to 2945
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               2946 non-null   datetime64[us]
 1   USD_INR            2946 non-null   float64
 2   Oil                2946 non-null   float64
 3   DXY                2946 non-null   float64
 4   NIFTY              2946 non-null   float64
 5   ForexReserves      2946 non-null   float64
 6   GoldReserves       2946 non-null   float64
 7   TotalReserves      2946 non-null   float64
 8   Inflation          2946 non-null   float64
 9   NetFlow            2946 non-null   float64
 10  INR_Return         2946 non-null   float64
 11  Oil_Change         2946 non-null   float64
 12  DXY_Change         2946 non-null   float64
 13  INR_Volatility_7D  2946 non-null   float64
 14  CrisisFlag         2946 non-null   int32
dtypes: datetime64[us](1), float64(13), int32(1)
memory usage: 333.9 KB
None
Date                 0
USD_INR              0
Oil                  0
DXY                  0
NIFTY                0
ForexReserves        0
GoldReserves         0
TotalReserves        0
Inflation            0
NetFlow              0
INR_Return           0
Oil_Change           0
DXY_Change           0
INR_Volatility_7D    0
CrisisFlag           0
dtype: int64

In [ ]:
master.to_csv(
    "C:\\Users\\ka843\\Coding\\Ruppee-Instability-Dashboard-and-pridictor\\data\\processed\\master_dataset.csv",
    index=False
)

print(
    "Master Dataset Created Successfully"
)